# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e7158341c3959c8fe42891b0b851ae51"
name = "AI Theme Assistant"
application_url = "https://shopify-ai-theme-studio-57f25a48.base44.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_online_store_pages,write_online_store_pages,read_products,read_content,write_content,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify-ai-theme-studio-57f25a48.base44.app/auth/callback",
  "https://shopify-ai-theme-studio-57f25a48.base44.app/auth/shopify/callback"
]

# App Navigation is now configured in the Partner Dashboard
